### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by mark-zarandi** [Drakulix/spotify-sensor#1]
can you give some more installation instructions?  What do I do once i have it installed in HACS?  I don't understand what you mean by "it can be setup in the UI."

**Comment by mark-zarandi** [comment]
It ain't showing up in integrations.

**Comment by Drakulix** [comment]
It should show up in the integrations, once you added it via HACS (by adding this repository as a custom-respository and then installing normally via HACS).
However it may very well be, that recent HA versions have broken this integration. I have no use any more for this and have no tried to use it for the better part of this year.
I should mark it as archived to reflect that.

Basically, I can't really provide any support for this any more and if you don't feel like diving into the python code, I can't really help you.
But the code is not complicated and I am glad to provide some help understanding what it does, if you feel like it.

**Comment by mark-zarandi** [comment]
10-4, thanks.
